package PlayTombola;

import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.*;

public class Tombola extends javax.swing.JFrame {

    /**
     * Creates new form Tombola
     */
    protected final Numbers n; //PrintLog extends Tombola
    private final List<JButton> buttonsList;

    public Tombola() {
        initComponents();
        n = new Numbers();
        buttonsList = Arrays.asList(
                num1, num2, num3, num4, num5, num6, num7, num8, num9, num10,
                num11, num12, num13, num14, num15, num16, num17, num18, num19, num20,
                num21, num22, num23, num24, num25, num26, num27, num28, num29, num30,
                num31, num32, num33, num34, num35, num36, num37, num38, num39, num40,
                num41, num42, num43, num44, num45, num46, num47, num48, num49, num50,
                num51, num52, num53, num54, num55, num56, num57, num58, num59, num60,
                num61, num62, num63, num64, num65, num66, num67, num68, num69, num70,
                num71, num72, num73, num74, num75, num76, num77, num78, num79, num80,
                num81, num82, num83, num84, num85, num86, num87, num88, num89, num90
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        num61 = new javax.swing.JButton();
        num85 = new javax.swing.JButton();
        num65 = new javax.swing.JButton();
        num83 = new javax.swing.JButton();
        num63 = new javax.swing.JButton();
        num81 = new javax.swing.JButton();
        num82 = new javax.swing.JButton();
        num75 = new javax.swing.JButton();
        num74 = new javax.swing.JButton();
        num84 = new javax.swing.JButton();
        num71 = new javax.swing.JButton();
        num73 = new javax.swing.JButton();
        num72 = new javax.swing.JButton();
        num62 = new javax.swing.JButton();
        num64 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        num49 = new javax.swing.JButton();
        num39 = new javax.swing.JButton();
        num40 = new javax.swing.JButton();
        num38 = new javax.swing.JButton();
        num47 = new javax.swing.JButton();
        num37 = new javax.swing.JButton();
        num58 = new javax.swing.JButton();
        num60 = new javax.swing.JButton();
        num48 = new javax.swing.JButton();
        num56 = new javax.swing.JButton();
        num57 = new javax.swing.JButton();
        num36 = new javax.swing.JButton();
        num59 = new javax.swing.JButton();
        num46 = new javax.swing.JButton();
        num50 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        num88 = new javax.swing.JButton();
        num67 = new javax.swing.JButton();
        num66 = new javax.swing.JButton();
        num87 = new javax.swing.JButton();
        num69 = new javax.swing.JButton();
        num90 = new javax.swing.JButton();
        num79 = new javax.swing.JButton();
        num89 = new javax.swing.JButton();
        num78 = new javax.swing.JButton();
        num77 = new javax.swing.JButton();
        num76 = new javax.swing.JButton();
        num70 = new javax.swing.JButton();
        num80 = new javax.swing.JButton();
        num86 = new javax.swing.JButton();
        num68 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        num44 = new javax.swing.JButton();
        num41 = new javax.swing.JButton();
        num42 = new javax.swing.JButton();
        num54 = new javax.swing.JButton();
        num53 = new javax.swing.JButton();
        num35 = new javax.swing.JButton();
        num31 = new javax.swing.JButton();
        num51 = new javax.swing.JButton();
        num32 = new javax.swing.JButton();
        num33 = new javax.swing.JButton();
        num45 = new javax.swing.JButton();
        num52 = new javax.swing.JButton();
        num34 = new javax.swing.JButton();
        num43 = new javax.swing.JButton();
        num55 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        num16 = new javax.swing.JButton();
        num29 = new javax.swing.JButton();
        num19 = new javax.swing.JButton();
        num26 = new javax.swing.JButton();
        num20 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num30 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num28 = new javax.swing.JButton();
        num18 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num10 = new javax.swing.JButton();
        num17 = new javax.swing.JButton();
        num27 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        num25 = new javax.swing.JButton();
        num24 = new javax.swing.JButton();
        num23 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num11 = new javax.swing.JButton();
        num15 = new javax.swing.JButton();
        num13 = new javax.swing.JButton();
        num21 = new javax.swing.JButton();
        num22 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num14 = new javax.swing.JButton();
        num12 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabelPrevious1 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jButtonPrintLog = new javax.swing.JButton();
        jButtonNextNumber = new javax.swing.JButton();
        jLabelPrevious = new javax.swing.JLabel();
        jLabelCurrentNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlayTombola");

        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        num61.setBackground(new java.awt.Color(0, 0, 255));
        num61.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num61.setForeground(new java.awt.Color(255, 255, 255));
        num61.setText("61");
        num61.setEnabled(false);

        num85.setBackground(new java.awt.Color(0, 0, 255));
        num85.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num85.setForeground(new java.awt.Color(255, 255, 255));
        num85.setText("85");
        num85.setEnabled(false);

        num65.setBackground(new java.awt.Color(0, 0, 255));
        num65.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num65.setForeground(new java.awt.Color(255, 255, 255));
        num65.setText("65");
        num65.setEnabled(false);

        num83.setBackground(new java.awt.Color(0, 0, 255));
        num83.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num83.setForeground(new java.awt.Color(255, 255, 255));
        num83.setText("83");
        num83.setEnabled(false);

        num63.setBackground(new java.awt.Color(0, 0, 255));
        num63.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num63.setForeground(new java.awt.Color(255, 255, 255));
        num63.setText("63");
        num63.setEnabled(false);

        num81.setBackground(new java.awt.Color(0, 0, 255));
        num81.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num81.setForeground(new java.awt.Color(255, 255, 255));
        num81.setText("81");
        num81.setEnabled(false);

        num82.setBackground(new java.awt.Color(0, 0, 255));
        num82.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num82.setForeground(new java.awt.Color(255, 255, 255));
        num82.setText("82");
        num82.setEnabled(false);

        num75.setBackground(new java.awt.Color(0, 0, 255));
        num75.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num75.setForeground(new java.awt.Color(255, 255, 255));
        num75.setText("75");
        num75.setEnabled(false);

        num74.setBackground(new java.awt.Color(0, 0, 255));
        num74.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num74.setForeground(new java.awt.Color(255, 255, 255));
        num74.setText("74");
        num74.setEnabled(false);

        num84.setBackground(new java.awt.Color(0, 0, 255));
        num84.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num84.setForeground(new java.awt.Color(255, 255, 255));
        num84.setText("84");
        num84.setEnabled(false);

        num71.setBackground(new java.awt.Color(0, 0, 255));
        num71.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num71.setForeground(new java.awt.Color(255, 255, 255));
        num71.setText("71");
        num71.setEnabled(false);

        num73.setBackground(new java.awt.Color(0, 0, 255));
        num73.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num73.setForeground(new java.awt.Color(255, 255, 255));
        num73.setText("73");
        num73.setEnabled(false);

        num72.setBackground(new java.awt.Color(0, 0, 255));
        num72.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num72.setForeground(new java.awt.Color(255, 255, 255));
        num72.setText("72");
        num72.setEnabled(false);

        num62.setBackground(new java.awt.Color(0, 0, 255));
        num62.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num62.setForeground(new java.awt.Color(255, 255, 255));
        num62.setText("62");
        num62.setEnabled(false);

        num64.setBackground(new java.awt.Color(0, 0, 255));
        num64.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num64.setForeground(new java.awt.Color(255, 255, 255));
        num64.setText("64");
        num64.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(num81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num85, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(num61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(num71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num61, num62, num63, num64, num65, num71, num72, num73, num74, num75, num81, num82, num83, num84, num85});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num61, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num62, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num63, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num64, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num65, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num71, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num72, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num73, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num74, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num75, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num81, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num82, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num83, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num84, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num85, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        num49.setBackground(new java.awt.Color(0, 0, 255));
        num49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num49.setForeground(new java.awt.Color(255, 255, 255));
        num49.setText("49");
        num49.setEnabled(false);

        num39.setBackground(new java.awt.Color(0, 0, 255));
        num39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num39.setForeground(new java.awt.Color(255, 255, 255));
        num39.setText("39");
        num39.setEnabled(false);

        num40.setBackground(new java.awt.Color(0, 0, 255));
        num40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num40.setForeground(new java.awt.Color(255, 255, 255));
        num40.setText("40");
        num40.setEnabled(false);

        num38.setBackground(new java.awt.Color(0, 0, 255));
        num38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num38.setForeground(new java.awt.Color(255, 255, 255));
        num38.setText("38");
        num38.setEnabled(false);

        num47.setBackground(new java.awt.Color(0, 0, 255));
        num47.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num47.setForeground(new java.awt.Color(255, 255, 255));
        num47.setText("47");
        num47.setEnabled(false);

        num37.setBackground(new java.awt.Color(0, 0, 255));
        num37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num37.setForeground(new java.awt.Color(255, 255, 255));
        num37.setText("37");
        num37.setEnabled(false);

        num58.setBackground(new java.awt.Color(0, 0, 255));
        num58.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num58.setForeground(new java.awt.Color(255, 255, 255));
        num58.setText("58");
        num58.setEnabled(false);

        num60.setBackground(new java.awt.Color(0, 0, 255));
        num60.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num60.setForeground(new java.awt.Color(255, 255, 255));
        num60.setText("60");
        num60.setEnabled(false);

        num48.setBackground(new java.awt.Color(0, 0, 255));
        num48.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num48.setForeground(new java.awt.Color(255, 255, 255));
        num48.setText("48");
        num48.setEnabled(false);

        num56.setBackground(new java.awt.Color(0, 0, 255));
        num56.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num56.setForeground(new java.awt.Color(255, 255, 255));
        num56.setText("56");
        num56.setEnabled(false);

        num57.setBackground(new java.awt.Color(0, 0, 255));
        num57.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num57.setForeground(new java.awt.Color(255, 255, 255));
        num57.setText("57");
        num57.setEnabled(false);

        num36.setBackground(new java.awt.Color(0, 0, 255));
        num36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num36.setForeground(new java.awt.Color(255, 255, 255));
        num36.setText("36");
        num36.setEnabled(false);

        num59.setBackground(new java.awt.Color(0, 0, 255));
        num59.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num59.setForeground(new java.awt.Color(255, 255, 255));
        num59.setText("59");
        num59.setEnabled(false);

        num46.setBackground(new java.awt.Color(0, 0, 255));
        num46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num46.setForeground(new java.awt.Color(255, 255, 255));
        num46.setText("46");
        num46.setEnabled(false);

        num50.setBackground(new java.awt.Color(0, 0, 255));
        num50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num50.setForeground(new java.awt.Color(255, 255, 255));
        num50.setText("50");
        num50.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(num36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num40, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(num46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(num56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num36, num37, num38, num39, num40, num46, num47, num48, num49, num50, num56, num57, num58, num59, num60});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num36, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num37, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num38, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num39, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num40, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num46, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num47, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num48, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num49, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num50, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num57, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num58, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num59, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num60, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num56, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        num88.setBackground(new java.awt.Color(0, 0, 255));
        num88.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num88.setForeground(new java.awt.Color(255, 255, 255));
        num88.setText("88");
        num88.setEnabled(false);

        num67.setBackground(new java.awt.Color(0, 0, 255));
        num67.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num67.setForeground(new java.awt.Color(255, 255, 255));
        num67.setText("67");
        num67.setEnabled(false);

        num66.setBackground(new java.awt.Color(0, 0, 255));
        num66.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num66.setForeground(new java.awt.Color(255, 255, 255));
        num66.setText("66");
        num66.setEnabled(false);

        num87.setBackground(new java.awt.Color(0, 0, 255));
        num87.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num87.setForeground(new java.awt.Color(255, 255, 255));
        num87.setText("87");
        num87.setEnabled(false);

        num69.setBackground(new java.awt.Color(0, 0, 255));
        num69.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num69.setForeground(new java.awt.Color(255, 255, 255));
        num69.setText("69");
        num69.setEnabled(false);

        num90.setBackground(new java.awt.Color(0, 0, 255));
        num90.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num90.setForeground(new java.awt.Color(255, 255, 255));
        num90.setText("90");
        num90.setEnabled(false);

        num79.setBackground(new java.awt.Color(0, 0, 255));
        num79.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num79.setForeground(new java.awt.Color(255, 255, 255));
        num79.setText("79");
        num79.setEnabled(false);

        num89.setBackground(new java.awt.Color(0, 0, 255));
        num89.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num89.setForeground(new java.awt.Color(255, 255, 255));
        num89.setText("89");
        num89.setEnabled(false);

        num78.setBackground(new java.awt.Color(0, 0, 255));
        num78.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num78.setForeground(new java.awt.Color(255, 255, 255));
        num78.setText("78");
        num78.setEnabled(false);

        num77.setBackground(new java.awt.Color(0, 0, 255));
        num77.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num77.setForeground(new java.awt.Color(255, 255, 255));
        num77.setText("77");
        num77.setEnabled(false);

        num76.setBackground(new java.awt.Color(0, 0, 255));
        num76.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num76.setForeground(new java.awt.Color(255, 255, 255));
        num76.setText("76");
        num76.setEnabled(false);

        num70.setBackground(new java.awt.Color(0, 0, 255));
        num70.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num70.setForeground(new java.awt.Color(255, 255, 255));
        num70.setText("70");
        num70.setEnabled(false);

        num80.setBackground(new java.awt.Color(0, 0, 255));
        num80.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num80.setForeground(new java.awt.Color(255, 255, 255));
        num80.setText("80");
        num80.setEnabled(false);

        num86.setBackground(new java.awt.Color(0, 0, 255));
        num86.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num86.setForeground(new java.awt.Color(255, 255, 255));
        num86.setText("86");
        num86.setEnabled(false);

        num68.setBackground(new java.awt.Color(0, 0, 255));
        num68.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num68.setForeground(new java.awt.Color(255, 255, 255));
        num68.setText("68");
        num68.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(num66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(num76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(num86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num90, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num66, num67, num68, num69, num70, num76, num77, num78, num79, num80, num86, num87, num88, num89, num90});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num66, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num67, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num68, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num69, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num70, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num76, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num77, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num78, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num79, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num80, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num87, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num88, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num89, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num90, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num86, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        num44.setBackground(new java.awt.Color(0, 0, 255));
        num44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num44.setForeground(new java.awt.Color(255, 255, 255));
        num44.setText("44");
        num44.setEnabled(false);

        num41.setBackground(new java.awt.Color(0, 0, 255));
        num41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num41.setForeground(new java.awt.Color(255, 255, 255));
        num41.setText("41");
        num41.setEnabled(false);

        num42.setBackground(new java.awt.Color(0, 0, 255));
        num42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num42.setForeground(new java.awt.Color(255, 255, 255));
        num42.setText("42");
        num42.setEnabled(false);

        num54.setBackground(new java.awt.Color(0, 0, 255));
        num54.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num54.setForeground(new java.awt.Color(255, 255, 255));
        num54.setText("54");
        num54.setEnabled(false);

        num53.setBackground(new java.awt.Color(0, 0, 255));
        num53.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num53.setForeground(new java.awt.Color(255, 255, 255));
        num53.setText("53");
        num53.setEnabled(false);

        num35.setBackground(new java.awt.Color(0, 0, 255));
        num35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num35.setForeground(new java.awt.Color(255, 255, 255));
        num35.setText("35");
        num35.setEnabled(false);

        num31.setBackground(new java.awt.Color(0, 0, 255));
        num31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num31.setForeground(new java.awt.Color(255, 255, 255));
        num31.setText("31");
        num31.setBorder(null);
        num31.setEnabled(false);

        num51.setBackground(new java.awt.Color(0, 0, 255));
        num51.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num51.setForeground(new java.awt.Color(255, 255, 255));
        num51.setText("51");
        num51.setEnabled(false);

        num32.setBackground(new java.awt.Color(0, 0, 255));
        num32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num32.setForeground(new java.awt.Color(255, 255, 255));
        num32.setText("32");
        num32.setEnabled(false);

        num33.setBackground(new java.awt.Color(0, 0, 255));
        num33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num33.setForeground(new java.awt.Color(255, 255, 255));
        num33.setText("33");
        num33.setEnabled(false);

        num45.setBackground(new java.awt.Color(0, 0, 255));
        num45.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num45.setForeground(new java.awt.Color(255, 255, 255));
        num45.setText("45");
        num45.setEnabled(false);

        num52.setBackground(new java.awt.Color(0, 0, 255));
        num52.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num52.setForeground(new java.awt.Color(255, 255, 255));
        num52.setText("52");
        num52.setEnabled(false);

        num34.setBackground(new java.awt.Color(0, 0, 255));
        num34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num34.setForeground(new java.awt.Color(255, 255, 255));
        num34.setText("34");
        num34.setEnabled(false);

        num43.setBackground(new java.awt.Color(0, 0, 255));
        num43.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num43.setForeground(new java.awt.Color(255, 255, 255));
        num43.setText("43");
        num43.setEnabled(false);

        num55.setBackground(new java.awt.Color(0, 0, 255));
        num55.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num55.setForeground(new java.awt.Color(255, 255, 255));
        num55.setText("55");
        num55.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(num31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num35, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(num41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(num51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num31, num32, num33, num34, num35, num41, num42, num43, num44, num45, num51, num52, num53, num54, num55});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num31, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num32, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num33, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num34, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num35, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num41, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num42, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num43, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num44, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num45, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num52, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num53, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num54, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num55, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num51, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        num16.setBackground(new java.awt.Color(0, 0, 255));
        num16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num16.setForeground(new java.awt.Color(255, 255, 255));
        num16.setText("16");
        num16.setEnabled(false);

        num29.setBackground(new java.awt.Color(0, 0, 255));
        num29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num29.setForeground(new java.awt.Color(255, 255, 255));
        num29.setText("29");
        num29.setEnabled(false);

        num19.setBackground(new java.awt.Color(0, 0, 255));
        num19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num19.setForeground(new java.awt.Color(255, 255, 255));
        num19.setText("19");
        num19.setEnabled(false);

        num26.setBackground(new java.awt.Color(0, 0, 255));
        num26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num26.setForeground(new java.awt.Color(255, 255, 255));
        num26.setText("26");
        num26.setEnabled(false);

        num20.setBackground(new java.awt.Color(0, 0, 255));
        num20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num20.setForeground(new java.awt.Color(255, 255, 255));
        num20.setText("20");
        num20.setEnabled(false);

        num6.setBackground(new java.awt.Color(0, 0, 255));
        num6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num6.setForeground(new java.awt.Color(255, 255, 255));
        num6.setText("6");
        num6.setEnabled(false);

        num30.setBackground(new java.awt.Color(0, 0, 255));
        num30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num30.setForeground(new java.awt.Color(255, 255, 255));
        num30.setText("30");
        num30.setEnabled(false);

        num7.setBackground(new java.awt.Color(0, 0, 255));
        num7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num7.setForeground(new java.awt.Color(255, 255, 255));
        num7.setText("7");
        num7.setEnabled(false);

        num28.setBackground(new java.awt.Color(0, 0, 255));
        num28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num28.setForeground(new java.awt.Color(255, 255, 255));
        num28.setText("28");
        num28.setEnabled(false);

        num18.setBackground(new java.awt.Color(0, 0, 255));
        num18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num18.setForeground(new java.awt.Color(255, 255, 255));
        num18.setText("18");
        num18.setEnabled(false);

        num8.setBackground(new java.awt.Color(0, 0, 255));
        num8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num8.setForeground(new java.awt.Color(255, 255, 255));
        num8.setText("8");
        num8.setEnabled(false);

        num9.setBackground(new java.awt.Color(0, 0, 255));
        num9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num9.setForeground(new java.awt.Color(255, 255, 255));
        num9.setText("9");
        num9.setEnabled(false);

        num10.setBackground(new java.awt.Color(0, 0, 255));
        num10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num10.setForeground(new java.awt.Color(255, 255, 255));
        num10.setText("10");
        num10.setEnabled(false);

        num17.setBackground(new java.awt.Color(0, 0, 255));
        num17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num17.setForeground(new java.awt.Color(255, 255, 255));
        num17.setText("17");
        num17.setEnabled(false);

        num27.setBackground(new java.awt.Color(0, 0, 255));
        num27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num27.setForeground(new java.awt.Color(255, 255, 255));
        num27.setText("27");
        num27.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(num16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(num26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num30, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num10, num16, num17, num18, num19, num20, num26, num27, num28, num29, num30, num6, num7, num8, num9});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num17, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num18, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num20, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num26, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num27, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num28, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num29, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num30, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        num25.setBackground(new java.awt.Color(0, 0, 255));
        num25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num25.setForeground(new java.awt.Color(255, 255, 255));
        num25.setText("25");
        num25.setEnabled(false);

        num24.setBackground(new java.awt.Color(0, 0, 255));
        num24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num24.setForeground(new java.awt.Color(255, 255, 255));
        num24.setText("24");
        num24.setEnabled(false);

        num23.setBackground(new java.awt.Color(0, 0, 255));
        num23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num23.setForeground(new java.awt.Color(255, 255, 255));
        num23.setText("23");
        num23.setEnabled(false);

        num4.setBackground(new java.awt.Color(0, 0, 255));
        num4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num4.setForeground(new java.awt.Color(255, 255, 255));
        num4.setText("4");
        num4.setEnabled(false);

        num5.setBackground(new java.awt.Color(0, 0, 255));
        num5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num5.setForeground(new java.awt.Color(255, 255, 255));
        num5.setText("5");
        num5.setEnabled(false);

        num11.setBackground(new java.awt.Color(0, 0, 255));
        num11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num11.setForeground(new java.awt.Color(255, 255, 255));
        num11.setText("11");
        num11.setEnabled(false);

        num15.setBackground(new java.awt.Color(0, 0, 255));
        num15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num15.setForeground(new java.awt.Color(255, 255, 255));
        num15.setText("15");
        num15.setEnabled(false);

        num13.setBackground(new java.awt.Color(0, 0, 255));
        num13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num13.setForeground(new java.awt.Color(255, 255, 255));
        num13.setText("13");
        num13.setEnabled(false);

        num21.setBackground(new java.awt.Color(0, 0, 255));
        num21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num21.setForeground(new java.awt.Color(255, 255, 255));
        num21.setText("21");
        num21.setEnabled(false);

        num22.setBackground(new java.awt.Color(0, 0, 255));
        num22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num22.setForeground(new java.awt.Color(255, 255, 255));
        num22.setText("22");
        num22.setEnabled(false);

        num1.setBackground(new java.awt.Color(0, 0, 255));
        num1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setText("1");
        num1.setEnabled(false);

        num2.setBackground(new java.awt.Color(0, 0, 255));
        num2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setText("2");
        num2.setEnabled(false);

        num3.setBackground(new java.awt.Color(0, 0, 255));
        num3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num3.setForeground(new java.awt.Color(255, 255, 255));
        num3.setText("3");
        num3.setEnabled(false);

        num14.setBackground(new java.awt.Color(0, 0, 255));
        num14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num14.setForeground(new java.awt.Color(255, 255, 255));
        num14.setText("14");
        num14.setEnabled(false);

        num12.setBackground(new java.awt.Color(0, 0, 255));
        num12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num12.setForeground(new java.awt.Color(255, 255, 255));
        num12.setText("12");
        num12.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num1, num11, num12, num13, num14, num15, num2, num21, num22, num23, num24, num3, num4, num5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num21, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num22, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num24, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num25, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2, jPanel3, jPanel4, jPanel5, jPanel6});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2, jPanel3, jPanel4, jPanel5, jPanel6});

        jLabelPrevious1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPrevious1.setText("0");

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonPrintLog.setText("Print Log");
        jButtonPrintLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintLogActionPerformed(evt);
            }
        });

        jButtonNextNumber.setText("Next Number");
        jButtonNextNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextNumberActionPerformed(evt);
            }
        });

        jLabelPrevious.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPrevious.setText("Previous:");

        jLabelCurrentNum.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelPrevious1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(137, 137, 137)
                .addComponent(jButtonNextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabelCurrentNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrintLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonPrintLog, jButtonReset});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCurrentNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNextNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jButtonPrintLog, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addGap(3, 3, 3)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jLabelPrevious1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelPrevious, jLabelPrevious1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonNextNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextNumberActionPerformed
        //next number button        

        //get random number (1 - numberList.size)
        Random ran = new Random();
        int size = n.getSize();
        if (size == 100) {
            JOptionPane.showMessageDialog(this, "End!");
        } else {

            int randomNum = ran.nextInt(n.getSize() - 0) + 0;

            // number in random index
            int number = n.getNum(randomNum);

            System.out.println(number);

            for (JButton b : buttonsList) {
                //if buttonText == number
                if (b.getText().equals(Integer.toString(number))) {

                    //enable number in window
                    b.setEnabled(true);
                }
            }
            //print current number on window label
            jLabelCurrentNum.setText(Integer.toString(number));
            //print previous number on window previous label (if previous number stack is empty print 0)
            if (n.getPreviousNUm() == 100) {

                jLabelPrevious1.setText(Integer.toString(0));
            } else {

                jLabelPrevious1.setText(Integer.toString(n.getPreviousNUm()));
            }
            //set current number to previous number stack
            n.setPreviousNum(number); //set that number to the List of previous numbers
        }
    }//GEN-LAST:event_jButtonNextNumberActionPerformed

    private void jButtonPrintLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintLogActionPerformed
        //print log button
        n.printLog();
        JOptionPane.showMessageDialog(this, "File printed!");
    }//GEN-LAST:event_jButtonPrintLogActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        //reset button
        n.reset();
        for (JButton b : buttonsList) {
            b.setEnabled(false);
        }
        jLabelPrevious1.setText(Integer.toString(0));
        jLabelCurrentNum.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tombola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tombola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tombola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tombola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tombola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNextNumber;
    private javax.swing.JButton jButtonPrintLog;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelCurrentNum;
    private javax.swing.JLabel jLabelPrevious;
    private javax.swing.JLabel jLabelPrevious1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num11;
    private javax.swing.JButton num12;
    private javax.swing.JButton num13;
    private javax.swing.JButton num14;
    private javax.swing.JButton num15;
    private javax.swing.JButton num16;
    private javax.swing.JButton num17;
    private javax.swing.JButton num18;
    private javax.swing.JButton num19;
    private javax.swing.JButton num2;
    private javax.swing.JButton num20;
    private javax.swing.JButton num21;
    private javax.swing.JButton num22;
    private javax.swing.JButton num23;
    private javax.swing.JButton num24;
    private javax.swing.JButton num25;
    private javax.swing.JButton num26;
    private javax.swing.JButton num27;
    private javax.swing.JButton num28;
    private javax.swing.JButton num29;
    private javax.swing.JButton num3;
    private javax.swing.JButton num30;
    private javax.swing.JButton num31;
    private javax.swing.JButton num32;
    private javax.swing.JButton num33;
    private javax.swing.JButton num34;
    private javax.swing.JButton num35;
    private javax.swing.JButton num36;
    private javax.swing.JButton num37;
    private javax.swing.JButton num38;
    private javax.swing.JButton num39;
    private javax.swing.JButton num4;
    private javax.swing.JButton num40;
    private javax.swing.JButton num41;
    private javax.swing.JButton num42;
    private javax.swing.JButton num43;
    private javax.swing.JButton num44;
    private javax.swing.JButton num45;
    private javax.swing.JButton num46;
    private javax.swing.JButton num47;
    private javax.swing.JButton num48;
    private javax.swing.JButton num49;
    private javax.swing.JButton num5;
    private javax.swing.JButton num50;
    private javax.swing.JButton num51;
    private javax.swing.JButton num52;
    private javax.swing.JButton num53;
    private javax.swing.JButton num54;
    private javax.swing.JButton num55;
    private javax.swing.JButton num56;
    private javax.swing.JButton num57;
    private javax.swing.JButton num58;
    private javax.swing.JButton num59;
    private javax.swing.JButton num6;
    private javax.swing.JButton num60;
    private javax.swing.JButton num61;
    private javax.swing.JButton num62;
    private javax.swing.JButton num63;
    private javax.swing.JButton num64;
    private javax.swing.JButton num65;
    private javax.swing.JButton num66;
    private javax.swing.JButton num67;
    private javax.swing.JButton num68;
    private javax.swing.JButton num69;
    private javax.swing.JButton num7;
    private javax.swing.JButton num70;
    private javax.swing.JButton num71;
    private javax.swing.JButton num72;
    private javax.swing.JButton num73;
    private javax.swing.JButton num74;
    private javax.swing.JButton num75;
    private javax.swing.JButton num76;
    private javax.swing.JButton num77;
    private javax.swing.JButton num78;
    private javax.swing.JButton num79;
    private javax.swing.JButton num8;
    private javax.swing.JButton num80;
    private javax.swing.JButton num81;
    private javax.swing.JButton num82;
    private javax.swing.JButton num83;
    private javax.swing.JButton num84;
    private javax.swing.JButton num85;
    private javax.swing.JButton num86;
    private javax.swing.JButton num87;
    private javax.swing.JButton num88;
    private javax.swing.JButton num89;
    private javax.swing.JButton num9;
    private javax.swing.JButton num90;
    // End of variables declaration//GEN-END:variables
}
